apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-openshift-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: geocache-detective
    repoURL: http://gitea-gitea.apps-crc.testing/johan974/argocd-openshift-local.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true