apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.28.0 (c4137012e)
    metallb.universe.tf/address-pool: default
  labels:
    io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
  name: {{ .Values.geocachedetectiveviewer.name }}
  namespace: default
spec:
  ports:
    - name: https
      port: {{ .Values.geocachedetectiveviewer.service.externalPort }}
      nodePort: 30777
      targetPort: {{ .Values.geocachedetectiveviewer.service.internalPort }}
  selector:
    io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
  type: NodePort