apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
  name: {{ .Values.geocachedetectiveviewer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
  strategy: {}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        io.kompose.network/devhome-default: "true"
        io.kompose.service: {{ .Values.geocachedetectiveviewer.name }}
    spec:
      containers:
        - name: {{ .Values.geocachedetectiveviewer.name }}
          image: {{ .Values.geocachedetectiveviewer.image.fulldigest5 }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.geocachedetectiveviewer.service.internalPort }}
          resources: {}
      restartPolicy: Always
