apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.geocachedetectiveapi.name }}
  name: {{ .Values.geocachedetectiveapi.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.geocachedetectiveapi.name }}
  strategy: {}
  revisionHistoryLimit: 0
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/devhome-default: "true"
        io.kompose.service: {{ .Values.geocachedetectiveapi.name }}
    spec:
      containers:
        - env:
            - name: management.endpoints.web.exposure.include
              value: "*"
            - name: management.info.env.enabled
              value: "true"
            - name: DETECTIVE_AUTH_ENABLED
              value: "false"
            - name: cors.allowedOrigins
              value: "http://localhost:8077,http://localhost:8777,http://localhost:8765"
            - name: spring.datasource.url
              value: jdbc:postgresql://postgres:5432/postgresdb
            - name: spring.datasource.username
              value: postgresuser
            - name: spring.datasource.password
              value: postgrespassword
            - name: spring.jpa.database-platform
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: spring.ai.openai.api-key
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: apikey
          image: {{ .Values.geocachedetectiveapi.image.fulldigest6 }}
          imagePullPolicy: Always
          name: {{ .Values.geocachedetectiveapi.name }}
          ports:
            - containerPort: {{ .Values.geocachedetectiveapi.service.internalPort }}
          resources: {}
      restartPolicy: Always