apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  ports:
    - name: "5432"
      targetPort: 5432
      port: 5432
      nodePort: 30432
  selector:
    app: postgres
  type: NodePort