apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  ports:
    - name: "5432"
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app: {{ .Values.postgres.name }}
  type: NodePort