apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  storageClassName: postgres-scn
  volumeName:       postgres-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi